
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.tum.in.dss.guestbook.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-06-30T22:57:12.284+02:00
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "GuestBookServiceLocator",
                      portName = "GuestBookServiceStarter",
                      targetNamespace = "http://dss.in.tum.de/guestbook/wsdl",
                      wsdlLocation = "classpath:guestbook.wsdl",
                      endpointInterface = "de.tum.in.dss.guestbook.wsdl.GuestBookService")
                      
public class GuestBookServiceImpl implements GuestBookService {

    private static final Logger LOG = Logger.getLogger(GuestBookServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#addGuestBookEntries(de.tum.in.dss.guestbook.Guestbook  request6PartInput )*
     */
    public int addGuestBookEntries(de.tum.in.dss.guestbook.Guestbook request6PartInput) { 
        LOG.info("Executing operation addGuestBookEntries");
        System.out.println(request6PartInput);
        try {
            int _return = -727315723;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#retrieveAllGuestBooks(*
     */
    public de.tum.in.dss.guestbook.Guestbook retrieveAllGuestBooks() { 
        LOG.info("Executing operation retrieveAllGuestBooks");
        try {
            de.tum.in.dss.guestbook.Guestbook _return = new de.tum.in.dss.guestbook.Guestbook();
            java.util.List<de.tum.in.dss.guestbooktype.Guestbooktype> _returnEntry = new java.util.ArrayList<de.tum.in.dss.guestbooktype.Guestbooktype>();
            de.tum.in.dss.guestbooktype.Guestbooktype _returnEntryVal1 = new de.tum.in.dss.guestbooktype.Guestbooktype();
            _returnEntryVal1.setBOOKID(-535957963);
            _returnEntryVal1.setAUTHORTITLE("AUTHORTITLE-1901147805");
            _returnEntryVal1.setAUTHORNAME("AUTHORNAME1627752401");
            _returnEntryVal1.setBOOKDATA("BOOKDATA-819671576");
            _returnEntryVal1.setGUESTEMAILID("GUESTEMAILID-1893659740");
            java.util.Date _returnEntryVal1DATEOFCREATION = null;
            _returnEntryVal1.setDATEOFCREATION(_returnEntryVal1DATEOFCREATION);
            java.util.Date _returnEntryVal1LASTMODIFICATIONDATE = null;
            _returnEntryVal1.setLASTMODIFICATIONDATE(_returnEntryVal1LASTMODIFICATIONDATE);
            de.tum.in.dss.keyword.Keywords _returnEntryVal1Keywords = new de.tum.in.dss.keyword.Keywords();
            java.util.List<java.lang.String> _returnEntryVal1KeywordsKeyword = new java.util.ArrayList<java.lang.String>();
            _returnEntryVal1Keywords.getKeyword().addAll(_returnEntryVal1KeywordsKeyword);
            _returnEntryVal1.setKeywords(_returnEntryVal1Keywords);
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#retrieveGuestBookListByKeywords(de.tum.in.dss.keyword.Keywords  request4PartInput )*
     */
    public de.tum.in.dss.guestbook.Guestbook retrieveGuestBookListByKeywords(de.tum.in.dss.keyword.Keywords request4PartInput) { 
        LOG.info("Executing operation retrieveGuestBookListByKeywords");
        System.out.println(request4PartInput);
        try {
            de.tum.in.dss.guestbook.Guestbook _return = new de.tum.in.dss.guestbook.Guestbook();
            java.util.List<de.tum.in.dss.guestbooktype.Guestbooktype> _returnEntry = new java.util.ArrayList<de.tum.in.dss.guestbooktype.Guestbooktype>();
            de.tum.in.dss.guestbooktype.Guestbooktype _returnEntryVal1 = new de.tum.in.dss.guestbooktype.Guestbooktype();
            _returnEntryVal1.setBOOKID(9162756);
            _returnEntryVal1.setAUTHORTITLE("AUTHORTITLE-1351369103");
            _returnEntryVal1.setAUTHORNAME("AUTHORNAME-541635829");
            _returnEntryVal1.setBOOKDATA("BOOKDATA1858270882");
            _returnEntryVal1.setGUESTEMAILID("GUESTEMAILID2040253433");
            java.util.Date _returnEntryVal1DATEOFCREATION = null;
            _returnEntryVal1.setDATEOFCREATION(_returnEntryVal1DATEOFCREATION);
            java.util.Date _returnEntryVal1LASTMODIFICATIONDATE = null;
            _returnEntryVal1.setLASTMODIFICATIONDATE(_returnEntryVal1LASTMODIFICATIONDATE);
            de.tum.in.dss.keyword.Keywords _returnEntryVal1Keywords = new de.tum.in.dss.keyword.Keywords();
            java.util.List<java.lang.String> _returnEntryVal1KeywordsKeyword = new java.util.ArrayList<java.lang.String>();
            _returnEntryVal1Keywords.getKeyword().addAll(_returnEntryVal1KeywordsKeyword);
            _returnEntryVal1.setKeywords(_returnEntryVal1Keywords);
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#retrieveGuestBookListByKeywordsInText(de.tum.in.dss.keyword.Keywords  request3PartInput )*
     */
    public de.tum.in.dss.guestbook.Guestbook retrieveGuestBookListByKeywordsInText(de.tum.in.dss.keyword.Keywords request3PartInput) { 
        LOG.info("Executing operation retrieveGuestBookListByKeywordsInText");
        System.out.println(request3PartInput);
        try {
            de.tum.in.dss.guestbook.Guestbook _return = new de.tum.in.dss.guestbook.Guestbook();
            java.util.List<de.tum.in.dss.guestbooktype.Guestbooktype> _returnEntry = new java.util.ArrayList<de.tum.in.dss.guestbooktype.Guestbooktype>();
            de.tum.in.dss.guestbooktype.Guestbooktype _returnEntryVal1 = new de.tum.in.dss.guestbooktype.Guestbooktype();
            _returnEntryVal1.setBOOKID(835402439);
            _returnEntryVal1.setAUTHORTITLE("AUTHORTITLE2107519262");
            _returnEntryVal1.setAUTHORNAME("AUTHORNAME751220159");
            _returnEntryVal1.setBOOKDATA("BOOKDATA-1763873759");
            _returnEntryVal1.setGUESTEMAILID("GUESTEMAILID1484307081");
            java.util.Date _returnEntryVal1DATEOFCREATION = null;
            _returnEntryVal1.setDATEOFCREATION(_returnEntryVal1DATEOFCREATION);
            java.util.Date _returnEntryVal1LASTMODIFICATIONDATE = null;
            _returnEntryVal1.setLASTMODIFICATIONDATE(_returnEntryVal1LASTMODIFICATIONDATE);
            de.tum.in.dss.keyword.Keywords _returnEntryVal1Keywords = new de.tum.in.dss.keyword.Keywords();
            java.util.List<java.lang.String> _returnEntryVal1KeywordsKeyword = new java.util.ArrayList<java.lang.String>();
            _returnEntryVal1Keywords.getKeyword().addAll(_returnEntryVal1KeywordsKeyword);
            _returnEntryVal1.setKeywords(_returnEntryVal1Keywords);
            _returnEntry.add(_returnEntryVal1);
            _return.getEntry().addAll(_returnEntry);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#deleteGuestBook(de.tum.in.dss.guestbooktype.Guestbooktype  request9PartInput )*
     */
    public int deleteGuestBook(de.tum.in.dss.guestbooktype.Guestbooktype request9PartInput) { 
        LOG.info("Executing operation deleteGuestBook");
        System.out.println(request9PartInput);
        try {
            int _return = -1305256399;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#retrieveGuestBookKeywords(de.tum.in.dss.keyword.Keywords  request5PartInput )*
     */
    public de.tum.in.dss.keyword.Keywords retrieveGuestBookKeywords(de.tum.in.dss.keyword.Keywords request5PartInput) { 
        LOG.info("Executing operation retrieveGuestBookKeywords");
        System.out.println(request5PartInput);
        try {
            de.tum.in.dss.keyword.Keywords _return = new de.tum.in.dss.keyword.Keywords();
            java.util.List<java.lang.String> _returnKeyword = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnKeywordVal1 = "_returnKeywordVal-490166330";
            _returnKeyword.add(_returnKeywordVal1);
            _return.getKeyword().addAll(_returnKeyword);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#updateGuestBookEntry(de.tum.in.dss.guestbooktype.Guestbooktype  request8PartInput )*
     */
    public int updateGuestBookEntry(de.tum.in.dss.guestbooktype.Guestbooktype request8PartInput) { 
        LOG.info("Executing operation updateGuestBookEntry");
        System.out.println(request8PartInput);
        try {
            int _return = 1412751194;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#retrieveGuestBookByGuestBookId(int  request2PartInput )*
     */
    public de.tum.in.dss.guestbooktype.Guestbooktype retrieveGuestBookByGuestBookId(int request2PartInput) { 
        LOG.info("Executing operation retrieveGuestBookByGuestBookId");
        System.out.println(request2PartInput);
        try {
            de.tum.in.dss.guestbooktype.Guestbooktype _return = new de.tum.in.dss.guestbooktype.Guestbooktype();
            _return.setBOOKID(-2092393613);
            _return.setAUTHORTITLE("AUTHORTITLE1265253718");
            _return.setAUTHORNAME("AUTHORNAME1693852006");
            _return.setBOOKDATA("BOOKDATA2050706263");
            _return.setGUESTEMAILID("GUESTEMAILID-1964053617");
            java.util.Date _returnDATEOFCREATION = null;
            _return.setDATEOFCREATION(_returnDATEOFCREATION);
            java.util.Date _returnLASTMODIFICATIONDATE = null;
            _return.setLASTMODIFICATIONDATE(_returnLASTMODIFICATIONDATE);
            de.tum.in.dss.keyword.Keywords _returnKeywords = new de.tum.in.dss.keyword.Keywords();
            java.util.List<java.lang.String> _returnKeywordsKeyword = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnKeywordsKeywordVal1 = "_returnKeywordsKeywordVal-1609839721";
            _returnKeywordsKeyword.add(_returnKeywordsKeywordVal1);
            _returnKeywords.getKeyword().addAll(_returnKeywordsKeyword);
            _return.setKeywords(_returnKeywords);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.tum.in.dss.guestbook.wsdl.GuestBookService#createGuestBookEntry(de.tum.in.dss.guestbooktype.Guestbooktype  request7PartInput )*
     */
    public int createGuestBookEntry(de.tum.in.dss.guestbooktype.Guestbooktype request7PartInput) { 
        LOG.info("Executing operation createGuestBookEntry");
        System.out.println(request7PartInput);
        try {
            int _return = -453066476;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
