package de.tum.in.dss.guestbook.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-06-30T22:57:12.325+02:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "GuestBookServiceLocator", 
                  wsdlLocation = "classpath:guestbook.wsdl",
                  targetNamespace = "http://dss.in.tum.de/guestbook/wsdl") 
public class GuestBookServiceLocator extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dss.in.tum.de/guestbook/wsdl", "GuestBookServiceLocator");
    public final static QName GuestBookServiceStarter = new QName("http://dss.in.tum.de/guestbook/wsdl", "GuestBookServiceStarter");
    static {
        URL url = GuestBookServiceLocator.class.getClassLoader().getResource("guestbook.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GuestBookServiceLocator.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:guestbook.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public GuestBookServiceLocator(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GuestBookServiceLocator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GuestBookServiceLocator() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GuestBookServiceLocator(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GuestBookServiceLocator(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GuestBookServiceLocator(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GuestBookService
     */
    @WebEndpoint(name = "GuestBookServiceStarter")
    public GuestBookService getGuestBookServiceStarter() {
        return super.getPort(GuestBookServiceStarter, GuestBookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GuestBookService
     */
    @WebEndpoint(name = "GuestBookServiceStarter")
    public GuestBookService getGuestBookServiceStarter(WebServiceFeature... features) {
        return super.getPort(GuestBookServiceStarter, GuestBookService.class, features);
    }

}
