package de.tum.in.dss.guestbook.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-06-30T22:57:12.306+02:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", name = "GuestBookService")
@XmlSeeAlso({de.tum.in.dss.guestbook.ObjectFactory.class, ObjectFactory.class, de.tum.in.dss.guestbooktype.ObjectFactory.class, de.tum.in.dss.keyword.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GuestBookService {

    @WebResult(name = "resultcount1", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request6PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/addGuestBookEntries")
    public int addGuestBookEntries(
        @WebParam(partName = "request6PartInput", name = "guestbook", targetNamespace = "http://dss.in.tum.de/guestbook")
        de.tum.in.dss.guestbook.Guestbook request6PartInput
    );

    @WebResult(name = "guestbook", targetNamespace = "http://dss.in.tum.de/guestbook", partName = "request1PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/retrieveAllGuestBooks")
    public de.tum.in.dss.guestbook.Guestbook retrieveAllGuestBooks();

    @WebResult(name = "guestbook", targetNamespace = "http://dss.in.tum.de/guestbook", partName = "request4PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/retrieveGuestBookListByKeywords")
    public de.tum.in.dss.guestbook.Guestbook retrieveGuestBookListByKeywords(
        @WebParam(partName = "request4PartInput", name = "keywords2", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.keyword.Keywords request4PartInput
    );

    @WebResult(name = "guestbook", targetNamespace = "http://dss.in.tum.de/guestbook", partName = "request3PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/retrieveGuestBookListByKeywordsInText")
    public de.tum.in.dss.guestbook.Guestbook retrieveGuestBookListByKeywordsInText(
        @WebParam(partName = "request3PartInput", name = "keywords1", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.keyword.Keywords request3PartInput
    );

    @WebResult(name = "resultcount4", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request9PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/deleteGuestBook")
    public int deleteGuestBook(
        @WebParam(partName = "request9PartInput", name = "guestBooktype3", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.guestbooktype.Guestbooktype request9PartInput
    );

    @WebResult(name = "keywords4", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request5PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/retrieveGuestBookKeywords")
    public de.tum.in.dss.keyword.Keywords retrieveGuestBookKeywords(
        @WebParam(partName = "request5PartInput", name = "keywords3", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.keyword.Keywords request5PartInput
    );

    @WebResult(name = "resultcount3", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request8PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/updateGuestBookEntry")
    public int updateGuestBookEntry(
        @WebParam(partName = "request8PartInput", name = "guestBooktype2", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.guestbooktype.Guestbooktype request8PartInput
    );

    @WebResult(name = "guestBooktype", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request2PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/retrieveGuestBookByGuestBookId")
    public de.tum.in.dss.guestbooktype.Guestbooktype retrieveGuestBookByGuestBookId(
        @WebParam(partName = "request2PartInput", name = "guestBookId", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        int request2PartInput
    );

    @WebResult(name = "resultcount2", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl", partName = "request7PartOutput")
    @WebMethod(action = "http://dss.in.tum.de/guestbook/wsdl/createGuestBookEntry")
    public int createGuestBookEntry(
        @WebParam(partName = "request7PartInput", name = "guestBooktype1", targetNamespace = "http://dss.in.tum.de/guestbook/wsdl")
        de.tum.in.dss.guestbooktype.Guestbooktype request7PartInput
    );
}
